#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

password=$YNH_APP_ARG_PASSWORD
ynh_app_setting_set --key=password --value="$password"

key=$(ynh_string_random)
ynh_app_setting_set --key=key --value="$key"

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing nodejs..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="A short description of the app" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL CUSDIS
#=================================================
ynh_script_progression "Installing $app..."

pushd $install_dir
	ynh_hide_warnings ynh_exec_as_app yarn install
	ynh_hide_warnings ynh_exec_as_app yarn run build
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
